### ISSUE TITLE
error =  english_bot.set_trainer(ChatterBotCorpusTrainer) AttributeError: 'ChatBot' object has no attribute 'set_trainer'

### ISSUE THREAD

**Issue by aspiringguru** [chamkank/flask-chatterbot#22]
I'm seeing this problem as below. 
no changes from the git repo, git clone, then pip install -r requirements.txt 

it looks like a problem within the chatterbot git repo, which is weird.

reported similar problem on the chatterbot git repo yesterday, hoping someone might spot what is going on or replicate my problem.

my current platform: windows 10, have also seen this problem on ubuntu 16.04

checking the package versions
 pip freeze | grep atter
ChatterBot==1.0.2
chatterbot-corpus==1.2.0

python app.py
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Matthew\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Matthew\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Matthew\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    english_bot.set_trainer(ChatterBotCorpusTrainer)
AttributeError: 'ChatBot' object has no attribute 'set_trainer'

**Comment by fanntom** [comment]
I'm getting the same issue on a fresh installation.

imbrianp@ubuntu:~/flask-chatterbot$ python3 app.py
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/imbrianp/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to /home/imbrianp/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/imbrianp/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    english_bot.set_trainer(ChatterBotCorpusTrainer)
AttributeError: 'ChatBot' object has no attribute 'set_trainer'

**Comment by aspiringguru** [comment]
Can you follow-up on my issue on the chatterbot git repo. The author indicated he couldn't identify the problem.

**Comment by ciberflaite** [comment]
Try with

**Comment by fzhcary** [comment]
I fixed this issue by change requirements.txt: 
ChatterBot==0.7.1

**Comment by Endogen** [comment]
> I fixed this issue by change requirements.txt:
> ChatterBot==0.7.1

That doesn't work for me. I'm getting an error while installing that dependency

**Comment by RishabGuggali** [comment]
I am getting these when i run it. please help me



C:\Users\rgugg\PycharmProjects\flask-chatterbot\venv\Scripts\python.exe C:/Users/rgugg/PycharmProjects/flask-chatterbot/app.py
Traceback (most recent call last):
  File "C:/Users/rgugg/PycharmProjects/flask-chatterbot/app.py", line 2, in <module>
    from chatterbot import ChatBot
  File "C:\Users\rgugg\PycharmProjects\flask-chatterbot\venv\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "C:\Users\rgugg\PycharmProjects\flask-chatterbot\venv\lib\site-packages\chatterbot\chatterbot.py", line 3, in <module>
    from chatterbot.logic import LogicAdapter
  File "C:\Users\rgugg\PycharmProjects\flask-chatterbot\venv\lib\site-packages\chatterbot\logic\__init__.py", line 1, in <module>
    from chatterbot.logic.logic_adapter import LogicAdapter
  File "C:\Users\rgugg\PycharmProjects\flask-chatterbot\venv\lib\site-packages\chatterbot\logic\logic_adapter.py", line 3, in <module>
    from chatterbot.search import IndexedTextSearch
  File "C:\Users\rgugg\PycharmProjects\flask-chatterbot\venv\lib\site-packages\chatterbot\search.py", line 1, in <module>
    from chatterbot.conversation import Statement
  File "C:\Users\rgugg\PycharmProjects\flask-chatterbot\venv\lib\site-packages\chatterbot\conversation.py", line 1, in <module>
    from pytz import UTC
ModuleNotFoundError: No module named 'pytz'

Process finished with exit code 1
